package honeytoken

import (
	"encoding/json"
	"time"
)

// LinkIncidentThreatRequest links an existing organization threat to an
// incident.
type LinkIncidentThreatRequest struct {
	ThreatID     string `json:"threat_id" binding:"required,uuid"`
	RelationType string `json:"relation_type" binding:"omitempty,oneof=PRIMARY RELATED SUPPORTING"`
}

// IncidentThreatResponse represents a threat linked to an incident.
type IncidentThreatResponse struct {
	ThreatID     string    `json:"threat_id"`
	ThreatCode   string    `json:"threat_code"`
	ThreatType   string    `json:"threat_type"`
	Severity     string    `json:"severity"`
	Status       string    `json:"status"`
	RelationType string    `json:"relation_type"`
	AddedBy      *string   `json:"added_by,omitempty"`
	AddedAt      time.Time `json:"added_at"`
}

// AddIncidentTimelineNoteRequest adds an investigator note to an incident.
type AddIncidentTimelineNoteRequest struct {
	Title       string          `json:"title" binding:"required,min=3,max=255"`
	Description *string         `json:"description,omitempty" binding:"omitempty,max=10000"`
	Metadata    json.RawMessage `json:"metadata,omitempty"`
}

// IncidentTimelineResponse represents a chronological incident activity.
type IncidentTimelineResponse struct {
	ID             string          `json:"id"`
	EventType      string          `json:"event_type"`
	Title          string          `json:"title"`
	Description    *string         `json:"description,omitempty"`
	PreviousStatus *string         `json:"previous_status,omitempty"`
	NewStatus      *string         `json:"new_status,omitempty"`
	ActorUserID    *string         `json:"actor_user_id,omitempty"`
	Metadata       json.RawMessage `json:"metadata,omitempty"`
	OccurredAt     time.Time       `json:"occurred_at"`
	CreatedAt      time.Time       `json:"created_at"`
}

// IncidentTimelineListQuery represents timeline pagination parameters.
type IncidentTimelineListQuery struct {
	EventType string `form:"event_type"`
	Page      int    `form:"page" binding:"omitempty,min=1"`
	PageSize  int    `form:"page_size" binding:"omitempty,min=1,max=100"`
}

// IncidentTimelineListResponse represents a paginated incident timeline.
type IncidentTimelineListResponse struct {
	Entries    []IncidentTimelineResponse `json:"entries"`
	Total      int64                      `json:"total"`
	Page       int                        `json:"page"`
	PageSize   int                        `json:"page_size"`
	TotalPages int                        `json:"total_pages"`
}

// AddIncidentEvidenceRequest registers evidence already collected or
// generated by a trusted Digital Defense Hub service.
type AddIncidentEvidenceRequest struct {
	EvidenceType string  `json:"evidence_type" binding:"required,oneof=FILE_EVENT PROTECTED_FILE HONEYTOKEN CANARY_FILE FILE_COPY LOG SCREENSHOT MEMORY_DUMP PROCESS_INFORMATION SYSTEM_ARTIFACT MEDIA REPORT OTHER"`
	EvidenceName string  `json:"evidence_name" binding:"required,min=1,max=255"`
	Description  *string `json:"description,omitempty" binding:"omitempty,max=10000"`

	ThreatID        *string `json:"threat_id,omitempty" binding:"omitempty,uuid"`
	FileEventID     *string `json:"file_event_id,omitempty" binding:"omitempty,uuid"`
	ProtectedFileID *string `json:"protected_file_id,omitempty" binding:"omitempty,uuid"`
	HoneytokenID    *string `json:"honeytoken_id,omitempty" binding:"omitempty,uuid"`
	CanaryFileID    *string `json:"canary_file_id,omitempty" binding:"omitempty,uuid"`

	OriginalFileName *string `json:"original_file_name,omitempty" binding:"omitempty,max=255"`
	MimeType         *string `json:"mime_type,omitempty" binding:"omitempty,max=255"`
	FileSizeBytes    *int64  `json:"file_size_bytes,omitempty" binding:"omitempty,gte=0"`

	EvidenceHash  *string `json:"evidence_hash,omitempty" binding:"omitempty,max=128"`
	HashAlgorithm string  `json:"hash_algorithm" binding:"omitempty,oneof=SHA256 SHA384 SHA512"`

	CollectedAt *string         `json:"collected_at,omitempty"`
	Metadata    json.RawMessage `json:"metadata,omitempty"`
}

// VerifyIncidentEvidenceRequest records an integrity verification result.
// The service validates the supplied hash against the original evidence hash.
type VerifyIncidentEvidenceRequest struct {
	CalculatedHash string `json:"calculated_hash" binding:"required,min=64,max=128"`
}

// IncidentEvidenceListQuery represents evidence list filters.
type IncidentEvidenceListQuery struct {
	EvidenceType    string `form:"evidence_type"`
	IntegrityStatus string `form:"integrity_status"`
	Page            int    `form:"page" binding:"omitempty,min=1"`
	PageSize        int    `form:"page_size" binding:"omitempty,min=1,max=100"`
}

// IncidentEvidenceResponse returns safe evidence metadata without exposing
// the internal physical storage path.
type IncidentEvidenceResponse struct {
	ID           string  `json:"id"`
	EvidenceCode string  `json:"evidence_code"`
	EvidenceType string  `json:"evidence_type"`
	EvidenceName string  `json:"evidence_name"`
	Description  *string `json:"description,omitempty"`

	ThreatID        *string `json:"threat_id,omitempty"`
	FileEventID     *string `json:"file_event_id,omitempty"`
	ProtectedFileID *string `json:"protected_file_id,omitempty"`
	HoneytokenID    *string `json:"honeytoken_id,omitempty"`
	CanaryFileID    *string `json:"canary_file_id,omitempty"`

	OriginalFileName *string `json:"original_file_name,omitempty"`
	MimeType         *string `json:"mime_type,omitempty"`
	FileSizeBytes    *int64  `json:"file_size_bytes,omitempty"`

	EvidenceHash    *string `json:"evidence_hash,omitempty"`
	HashAlgorithm   string  `json:"hash_algorithm"`
	IntegrityStatus string  `json:"integrity_status"`
	IsImmutable     bool    `json:"is_immutable"`

	CollectedBy *string    `json:"collected_by,omitempty"`
	VerifiedBy  *string    `json:"verified_by,omitempty"`
	CollectedAt time.Time  `json:"collected_at"`
	VerifiedAt  *time.Time `json:"verified_at,omitempty"`

	Metadata json.RawMessage `json:"metadata,omitempty"`

	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// IncidentEvidenceListResponse represents paginated incident evidence.
type IncidentEvidenceListResponse struct {
	Evidence   []IncidentEvidenceResponse `json:"evidence"`
	Total      int64                      `json:"total"`
	Page       int                        `json:"page"`
	PageSize   int                        `json:"page_size"`
	TotalPages int                        `json:"total_pages"`
}

// IncidentDetailsResponse combines an incident with linked investigation
// resources.
type IncidentDetailsResponse struct {
	Incident IncidentResponse           `json:"incident"`
	Threats  []IncidentThreatResponse   `json:"threats"`
	Timeline []IncidentTimelineResponse `json:"timeline"`
	Evidence []IncidentEvidenceResponse `json:"evidence"`
}
