-- ============================================================
-- FILE NAME  : 007_create_pre_encryption_detections.sql
-- PURPOSE    : Store pre-encryption ransomware detections
--              and their contributing file events
-- PROJECT    : Offline-First Cyber Security and
--              Digital Forensics Platform
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS pre_encryption_detections (
    id UUID NOT NULL DEFAULT gen_random_uuid(),

    detection_sequence BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    detection_code VARCHAR(80) NOT NULL,
    detection_fingerprint VARCHAR(128) NOT NULL,

    organization_id UUID NOT NULL,
    department_id UUID,

    threat_id UUID,
    incident_id UUID,

    device_identifier VARCHAR(255),
    device_name VARCHAR(255),

    process_id BIGINT,
    process_name VARCHAR(255),
    executable_path TEXT,

    parent_process_id BIGINT,
    parent_process_name VARCHAR(255),
    command_line TEXT,

    window_started_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    window_ended_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    window_duration_seconds NUMERIC(12, 3) NOT NULL,

    total_event_count INTEGER NOT NULL DEFAULT 0,
    unique_file_count INTEGER NOT NULL DEFAULT 0,
    unique_extension_count INTEGER NOT NULL DEFAULT 0,
    unique_process_count INTEGER NOT NULL DEFAULT 0,

    created_event_count INTEGER NOT NULL DEFAULT 0,
    modified_event_count INTEGER NOT NULL DEFAULT 0,
    renamed_event_count INTEGER NOT NULL DEFAULT 0,
    extension_changed_event_count INTEGER NOT NULL DEFAULT 0,
    deleted_event_count INTEGER NOT NULL DEFAULT 0,
    hash_changed_event_count INTEGER NOT NULL DEFAULT 0,
    permission_changed_event_count INTEGER NOT NULL DEFAULT 0,
    encrypted_event_count INTEGER NOT NULL DEFAULT 0,

    canary_event_count INTEGER NOT NULL DEFAULT 0,
    honeytoken_event_count INTEGER NOT NULL DEFAULT 0,
    protected_file_event_count INTEGER NOT NULL DEFAULT 0,

    high_entropy_write_count INTEGER NOT NULL DEFAULT 0,
    total_bytes_changed BIGINT NOT NULL DEFAULT 0,

    event_rate_per_minute NUMERIC(12, 3) NOT NULL DEFAULT 0,
    file_change_rate_per_minute NUMERIC(12, 3) NOT NULL DEFAULT 0,

    average_entropy_before NUMERIC(6, 4),
    average_entropy_after NUMERIC(6, 4),
    average_entropy_delta NUMERIC(6, 4),

    rule_score NUMERIC(5, 2) NOT NULL,
    ai_score NUMERIC(5, 2),
    combined_risk_score NUMERIC(5, 2) NOT NULL,
    threat_probability NUMERIC(5, 2),
    confidence_score NUMERIC(5, 2),

    risk_level VARCHAR(20) NOT NULL,
    classification VARCHAR(30) NOT NULL,
    detection_stage VARCHAR(30) NOT NULL,
    detection_method VARCHAR(30) NOT NULL DEFAULT 'HYBRID',

    risk_factors JSONB NOT NULL DEFAULT '{}'::jsonb,
    recommended_actions JSONB NOT NULL DEFAULT '[]'::jsonb,
    score_explanation TEXT,

    model_name VARCHAR(150),
    model_version VARCHAR(50),
    policy_version VARCHAR(50),

    requires_human_review BOOLEAN NOT NULL DEFAULT FALSE,
    requires_endpoint_isolation BOOLEAN NOT NULL DEFAULT FALSE,

    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    action_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,

    detected_at TIMESTAMP WITHOUT TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    reviewed_at TIMESTAMP WITHOUT TIME ZONE,
    mitigated_at TIMESTAMP WITHOUT TIME ZONE,

    created_at TIMESTAMP WITHOUT TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP WITHOUT TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pre_encryption_detections_pkey
        PRIMARY KEY (id),

    CONSTRAINT uq_pre_encryption_detection_sequence
        UNIQUE (detection_sequence),

    CONSTRAINT uq_pre_encryption_detection_code
        UNIQUE (
            organization_id,
            detection_code
        ),

    CONSTRAINT uq_pre_encryption_detection_fingerprint
        UNIQUE (
            organization_id,
            detection_fingerprint
        ),

    CONSTRAINT fk_pre_encryption_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_pre_encryption_department
        FOREIGN KEY (department_id)
        REFERENCES departments(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_pre_encryption_threat
        FOREIGN KEY (threat_id)
        REFERENCES threats(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_pre_encryption_incident
        FOREIGN KEY (incident_id)
        REFERENCES incidents(id)
        ON DELETE SET NULL,

    CONSTRAINT chk_pre_encryption_window
        CHECK (
            window_ended_at >= window_started_at
            AND window_duration_seconds >= 0
        ),

    CONSTRAINT chk_pre_encryption_process_ids
        CHECK (
            (process_id IS NULL OR process_id >= 0)
            AND (
                parent_process_id IS NULL
                OR parent_process_id >= 0
            )
        ),

    CONSTRAINT chk_pre_encryption_counts
        CHECK (
            total_event_count >= 0
            AND unique_file_count >= 0
            AND unique_extension_count >= 0
            AND unique_process_count >= 0
            AND created_event_count >= 0
            AND modified_event_count >= 0
            AND renamed_event_count >= 0
            AND extension_changed_event_count >= 0
            AND deleted_event_count >= 0
            AND hash_changed_event_count >= 0
            AND permission_changed_event_count >= 0
            AND encrypted_event_count >= 0
            AND canary_event_count >= 0
            AND honeytoken_event_count >= 0
            AND protected_file_event_count >= 0
            AND high_entropy_write_count >= 0
            AND total_bytes_changed >= 0
        ),

    CONSTRAINT chk_pre_encryption_rates
        CHECK (
            event_rate_per_minute >= 0
            AND file_change_rate_per_minute >= 0
        ),

    CONSTRAINT chk_pre_encryption_entropy_before
        CHECK (
            average_entropy_before IS NULL
            OR (
                average_entropy_before >= 0
                AND average_entropy_before <= 8
            )
        ),

    CONSTRAINT chk_pre_encryption_entropy_after
        CHECK (
            average_entropy_after IS NULL
            OR (
                average_entropy_after >= 0
                AND average_entropy_after <= 8
            )
        ),

    CONSTRAINT chk_pre_encryption_entropy_delta
        CHECK (
            average_entropy_delta IS NULL
            OR (
                average_entropy_delta >= -8
                AND average_entropy_delta <= 8
            )
        ),

    CONSTRAINT chk_pre_encryption_rule_score
        CHECK (
            rule_score >= 0
            AND rule_score <= 100
        ),

    CONSTRAINT chk_pre_encryption_ai_score
        CHECK (
            ai_score IS NULL
            OR (
                ai_score >= 0
                AND ai_score <= 100
            )
        ),

    CONSTRAINT chk_pre_encryption_combined_score
        CHECK (
            combined_risk_score >= 0
            AND combined_risk_score <= 100
        ),

    CONSTRAINT chk_pre_encryption_probability
        CHECK (
            threat_probability IS NULL
            OR (
                threat_probability >= 0
                AND threat_probability <= 100
            )
        ),

    CONSTRAINT chk_pre_encryption_confidence
        CHECK (
            confidence_score IS NULL
            OR (
                confidence_score >= 0
                AND confidence_score <= 100
            )
        ),

    CONSTRAINT chk_pre_encryption_risk_level
        CHECK (
            risk_level IN (
                'LOW',
                'MEDIUM',
                'HIGH',
                'CRITICAL'
            )
        ),

    CONSTRAINT chk_pre_encryption_classification
        CHECK (
            classification IN (
                'BENIGN',
                'SUSPICIOUS',
                'LIKELY_RANSOMWARE',
                'RANSOMWARE'
            )
        ),

    CONSTRAINT chk_pre_encryption_stage
        CHECK (
            detection_stage IN (
                'PRE_ENCRYPTION',
                'ENCRYPTION_SUSPECTED',
                'ENCRYPTION_CONFIRMED'
            )
        ),

    CONSTRAINT chk_pre_encryption_method
        CHECK (
            detection_method IN (
                'RULE_BASED',
                'AI_BASED',
                'HYBRID'
            )
        ),

    CONSTRAINT chk_pre_encryption_status
        CHECK (
            status IN (
                'OPEN',
                'INVESTIGATING',
                'CONFIRMED',
                'FALSE_POSITIVE',
                'MITIGATED',
                'ARCHIVED'
            )
        ),

    CONSTRAINT chk_pre_encryption_action_status
        CHECK (
            action_status IN (
                'PENDING',
                'NOT_REQUIRED',
                'REQUESTED',
                'COMPLETED',
                'FAILED'
            )
        ),

    CONSTRAINT chk_pre_encryption_risk_factors
        CHECK (
            jsonb_typeof(risk_factors) = 'object'
        ),

    CONSTRAINT chk_pre_encryption_recommended_actions
        CHECK (
            jsonb_typeof(recommended_actions) = 'array'
        ),

    CONSTRAINT chk_pre_encryption_metadata
        CHECK (
            jsonb_typeof(metadata) = 'object'
        )
);

CREATE TABLE IF NOT EXISTS pre_encryption_detection_events (
    id UUID NOT NULL DEFAULT gen_random_uuid(),

    organization_id UUID NOT NULL,
    detection_id UUID NOT NULL,
    file_event_id UUID NOT NULL,

    signal_types JSONB NOT NULL DEFAULT '[]'::jsonb,
    contribution_score NUMERIC(5, 2) NOT NULL DEFAULT 0,

    linked_at TIMESTAMP WITHOUT TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pre_encryption_detection_events_pkey
        PRIMARY KEY (id),

    CONSTRAINT uq_pre_encryption_detection_event
        UNIQUE (
            detection_id,
            file_event_id
        ),

    CONSTRAINT fk_pre_encryption_event_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_pre_encryption_event_detection
        FOREIGN KEY (detection_id)
        REFERENCES pre_encryption_detections(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_pre_encryption_event_file_event
        FOREIGN KEY (file_event_id)
        REFERENCES file_events(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_pre_encryption_signal_types
        CHECK (
            jsonb_typeof(signal_types) = 'array'
        ),

    CONSTRAINT chk_pre_encryption_contribution
        CHECK (
            contribution_score >= 0
            AND contribution_score <= 100
        )
);

CREATE INDEX IF NOT EXISTS idx_pre_encryption_org_detected
    ON pre_encryption_detections (
        organization_id,
        detected_at DESC
    );

CREATE INDEX IF NOT EXISTS idx_pre_encryption_device
    ON pre_encryption_detections (
        organization_id,
        device_identifier,
        detected_at DESC
    );

CREATE INDEX IF NOT EXISTS idx_pre_encryption_process
    ON pre_encryption_detections (
        organization_id,
        process_name,
        detected_at DESC
    );

CREATE INDEX IF NOT EXISTS idx_pre_encryption_risk
    ON pre_encryption_detections (
        risk_level,
        combined_risk_score DESC
    );

CREATE INDEX IF NOT EXISTS idx_pre_encryption_status
    ON pre_encryption_detections (
        status,
        detected_at DESC
    );

CREATE INDEX IF NOT EXISTS idx_pre_encryption_threat
    ON pre_encryption_detections (threat_id);

CREATE INDEX IF NOT EXISTS idx_pre_encryption_incident
    ON pre_encryption_detections (incident_id);

CREATE INDEX IF NOT EXISTS idx_pre_encryption_active
    ON pre_encryption_detections (
        organization_id,
        detected_at DESC
    )
    WHERE status IN (
        'OPEN',
        'INVESTIGATING',
        'CONFIRMED'
    );

CREATE INDEX IF NOT EXISTS idx_pre_encryption_event_detection
    ON pre_encryption_detection_events (detection_id);

CREATE INDEX IF NOT EXISTS idx_pre_encryption_event_file_event
    ON pre_encryption_detection_events (file_event_id);

CREATE INDEX IF NOT EXISTS idx_pre_encryption_event_organization
    ON pre_encryption_detection_events (
        organization_id,
        linked_at DESC
    );

COMMIT;