import { useCallback, useEffect, useMemo, useState } from "react";
import { Building2, Check, Clock3, Eye, LoaderCircle, Plus, Search, ShieldCheck, X } from "lucide-react";
import { api } from "../lib/api";
import { DashboardLiveBackground } from "../components/DashboardLiveBackground";

type Organization = { id:string; organization_code:string; legal_name:string; display_name:string; organization_type:string; primary_email:string; status:string; created_at:string };
type History = { action:string; reason?:string; actor_id?:string; created_at:string };
type Form = Record<"legal_name"|"organization_code"|"organization_type"|"primary_email"|"phone"|"address"|"admin_name"|"admin_email"|"admin_designation"|"admin_username"|"admin_password"|"admin_confirm_password"|"admin_first_name"|"admin_last_name"|"admin_employee_code"|"purpose",string>;
const blank:Form = { legal_name:"", organization_code:"", organization_type:"BUSINESS", primary_email:"", phone:"", address:"", admin_name:"", admin_email:"", admin_designation:"Organization Administrator", admin_username:"", admin_password:"", admin_confirm_password:"", admin_first_name:"", admin_last_name:"", admin_employee_code:"", purpose:"" };
const types = [["BUSINESS","Business"],["FINANCIAL","Bank / Financial"],["HEALTHCARE","Hospital"],["GOVERNMENT","Government"],["POLICE","Police"],["FORENSIC_LAB","Forensic Lab"],["RESEARCH_EDUCATION","Education"],["CYBERSECURITY_PROVIDER","Other"]] as const;
const when = (date?:string) => date ? new Date(date).toLocaleString() : "Not available";
const statusLabel = (value:string) => value === "ACTIVE" ? "Approved" : value.replaceAll("_", " ");

export function OrganizationManagementPage() {
  const [items,setItems] = useState<Organization[]>([]); const [query,setQuery] = useState(""); const [filter,setFilter] = useState("ALL");
  const [loading,setLoading] = useState(true); const [error,setError] = useState<string>(); const [drawer,setDrawer] = useState<Organization>();
  const [history,setHistory] = useState<History[]>([]); const [formOpen,setFormOpen] = useState(false); const [form,setForm] = useState<Form>(blank); const [saving,setSaving] = useState(false); const [reason,setReason] = useState(""); const [decision,setDecision] = useState<"approve"|"reject">();
  const load = useCallback(async()=>{ setLoading(true); try { setItems(await api.get<Organization[]>("/admin/organizations")); setError(undefined); } catch(cause) { setError(cause instanceof Error ? cause.message : "Unable to load organizations."); } finally { setLoading(false); } },[]);
  useEffect(()=>{ void load(); },[load]);
  const open = async (item:Organization) => { setDrawer(item); setHistory([]); const result=await api.get<History[]>(`/admin/organizations/${item.id}/history`).catch(()=>[]); setHistory(result); };
  const visible=useMemo(()=>items.filter(item => (filter==="ALL" || (filter==="APPROVED" ? item.status==="ACTIVE" : item.status===filter)) && `${item.legal_name} ${item.organization_code} ${item.primary_email}`.toLowerCase().includes(query.toLowerCase())),[items,filter,query]);
  const submit=async()=>{ setSaving(true); try { const {admin_confirm_password,...payload}=form; await api.post("/admin/organizations",{...payload,display_name:form.legal_name,security_email:form.primary_email}); setFormOpen(false); setForm(blank); await load(); } catch(cause) { setError(cause instanceof Error?cause.message:"Unable to create organization."); } finally { setSaving(false); } };
  const decide=async()=>{ if(!drawer||!decision) return; if(decision==="reject"&&!reason.trim()){setError("A rejection reason is required.");return;} setSaving(true); try { await api.put(`/admin/organizations/${drawer.id}/${decision}`,{reason}); setDecision(undefined); setReason(""); await load(); setDrawer(undefined); } catch(cause) { setError(cause instanceof Error?cause.message:"Decision could not be saved."); } finally { setSaving(false); } };
  return <section className="org-page"><DashboardLiveBackground/><header className="org-hero"><div><p className="eyebrow">SUPER ADMIN · TENANT GOVERNANCE</p><h1>Organizations</h1><span>Create, review, approve, and manage organizations across the platform.</span></div><div className="org-tools"><label><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search organizations..."/></label><button className="org-primary" onClick={()=>setFormOpen(true)}><Plus size={17}/>Create organization</button></div></header>
    {error&&<div className="alert alert-error">{error}<button onClick={()=>setError(undefined)}><X size={15}/></button></div>}
    <div className="org-panel"><nav className="org-filters">{["ALL","APPROVED","PENDING","REJECTED","SUSPENDED"].map(value=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{value==="ALL"?"All":statusLabel(value)}</button>)}</nav><div className="org-panel-head"><div><span>ORGANIZATION DIRECTORY</span><h2>Organization Directory</h2></div><small>{visible.length} organization(s)</small></div>{loading?<div className="resource-loading"><LoaderCircle className="spin"/>Loading organization directory…</div>:<div className="table-wrap"><table className="org-table"><thead><tr><th>Organization</th><th>Code</th><th>Type</th><th>Official email</th><th>Status</th><th>Created</th><th/></tr></thead><tbody>{visible.map(item=><tr key={item.id} onClick={()=>void open(item)}><td><strong><Building2 size={16}/>{item.display_name||item.legal_name}</strong><small>{item.legal_name}</small></td><td className="mono">{item.organization_code}</td><td>{item.organization_type.replaceAll("_"," ")}</td><td>{item.primary_email}</td><td><span className={`org-status ${item.status.toLowerCase()}`}>{statusLabel(item.status)}</span></td><td>{when(item.created_at)}</td><td><button aria-label="View organization" onClick={event=>{event.stopPropagation();void open(item)}}><Eye size={16}/></button></td></tr>)}</tbody></table>{!visible.length&&<div className="df-table-empty">No organizations match the selected filters.</div>}</div>}</div>
    {formOpen&&<div className="org-overlay"><form className="org-drawer" onSubmit={event=>{event.preventDefault();void submit();}}><header><div><span>CREATE ORGANIZATION</span><h2>Organization & Organization Admin</h2></div><button type="button" onClick={()=>setFormOpen(false)}><X/></button></header><p className="org-note">Creates the organization and its first Organization Admin in one audited transaction. This administrator has full access inside this organization only; platform Super Admins alone can access every organization.</p><div className="org-form">{([['legal_name','Organization name'],['organization_code','Organization code / Workspace ID'],['primary_email','Official email'],['phone','Organization contact number'],['address','Organization address'],['admin_first_name','Organization Admin first name'],['admin_last_name','Organization Admin last name'],['admin_username','Organization Admin username'],['admin_email','Organization Admin email'],['admin_password','Temporary password'],['admin_employee_code','Employee code'],['admin_designation','Designation'],['purpose','Notes / access purpose']] as [keyof Form,string][]).map(([key,label])=><label key={key}>{label}{key==="purpose"?<textarea value={form[key]} onChange={event=>setForm({...form,[key]:event.target.value})}/>:<input required={["legal_name","organization_code","primary_email","admin_first_name","admin_username","admin_email","admin_password"].includes(key)} minLength={key==="admin_password"?8:undefined} type={key==="admin_password"?"password":key.includes("email")?"email":"text"} value={form[key]} onChange={event=>setForm({...form,[key]:event.target.value,admin_name:key==="admin_first_name"?event.target.value+(form.admin_last_name?` ${form.admin_last_name}`:""):form.admin_name})}/>}</label>)}<label>Organization type<select value={form.organization_type} onChange={event=>setForm({...form,organization_type:event.target.value})}>{types.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><footer><button type="button" onClick={()=>setFormOpen(false)}>Cancel</button><button className="org-primary" disabled={saving}>{saving?<LoaderCircle className="spin"/>:<Plus/>}Create organization</button></footer></form></div>}
    {drawer&&<div className="org-overlay"><aside className="org-drawer org-details"><header><div><span>ORGANIZATION DETAILS</span><h2>{drawer.display_name||drawer.legal_name}</h2></div><button onClick={()=>setDrawer(undefined)}><X/></button></header><section><h3>Overview</h3><dl><div><dt>Organization code</dt><dd className="mono">{drawer.organization_code}</dd></div><div><dt>Type</dt><dd>{drawer.organization_type.replaceAll("_"," ")}</dd></div><div><dt>Official email</dt><dd>{drawer.primary_email}</dd></div><div><dt>Status</dt><dd><span className={`org-status ${drawer.status.toLowerCase()}`}>{statusLabel(drawer.status)}</span></dd></div><div><dt>Created</dt><dd>{when(drawer.created_at)}</dd></div></dl></section><section><h3>Approval history</h3>{history.length?<div className="org-timeline">{history.map((entry,index)=><article key={`${entry.created_at}-${index}`}><Clock3/><div><strong>{statusLabel(entry.action)}</strong><span>{entry.reason||"No additional reason recorded"}</span><time>{when(entry.created_at)}</time></div></article>)}</div>:<p className="muted">No approval-history record is available.</p>}</section>{drawer.status==="PENDING"&&<section className="org-actions"><h3>Review decision</h3><p>Approving activates this organization. Rejecting requires a recorded reason.</p><button className="org-primary" onClick={()=>setDecision("approve")}><Check/>Approve organization</button><button className="org-danger" onClick={()=>setDecision("reject")}>Reject organization</button></section>}<section className="org-api-note"><ShieldCheck/><span>Risk score, user counts, MFA coverage, incidents, cases, and security-event totals are not returned by the current organization API. They are intentionally not fabricated here.</span></section></aside></div>}
    {decision&&<div className="org-overlay"><div className="org-dialog"><h2>{decision==="approve"?"Approve organization and activate it?":"Reject organization"}</h2><p>{decision==="approve"?"The backend will activate this pending organization and record the approval.":"Provide a reason for the audit record."}</p><textarea placeholder="Decision reason" value={reason} onChange={event=>setReason(event.target.value)}/><footer><button onClick={()=>setDecision(undefined)}>Cancel</button><button className={decision==="approve"?"org-primary":"org-danger"} disabled={saving} onClick={()=>void decide()}>{saving?<LoaderCircle className="spin"/>:decision==="approve"?"Approve":"Reject"}</button></footer></div></div>}
  </section>;
}
